# Data Preparation 1

## Data Wrangling

Persiapan dataset sebelum dianalisa, terdiri dari beberapa format seperti pengelompokkan dan penggabungan

In [1]:
import pandas as pd
import numpy as np

In [2]:
#mengelompokkan dataset
team = {
             'rank':  [1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8],
             'team':  ['England','India','NewZealand','SouthAfrica','Pakistan','Australia','Bangladesh',
                       'SriLanka','India','England','South Africa','New Zealand','Pakistan','Australia',
                       'Bangladesh','SriLanka','England','India','NewZealand','SouthAfrica', 'Pakistan',
                       'Australia','Bangladesh','SriLanka'],
             'year':  [2016,2016,2016,2016,2016,2016,2016,2016,2017,2017,2017,2017,2017,2017,2017,2017,
                       2018,2018,2018,2018,2018,2018,2018,2018],
             'points': [4397,5310,3712,2834,3663,3888,2579,2463,4366,5710,3812,3834,3663,3088,2579,2563,
                        4397,5310,3712,2834,3663,3888,2579,2463]
            }

In [3]:
df_team = pd.DataFrame(team)
print(df_team)

    rank          team  year  points
0      1       England  2016    4397
1      2         India  2016    5310
2      3    NewZealand  2016    3712
3      4   SouthAfrica  2016    2834
4      5      Pakistan  2016    3663
5      6     Australia  2016    3888
6      7    Bangladesh  2016    2579
7      8      SriLanka  2016    2463
8      1         India  2017    4366
9      2       England  2017    5710
10     3  South Africa  2017    3812
11     4   New Zealand  2017    3834
12     5      Pakistan  2017    3663
13     6     Australia  2017    3088
14     7    Bangladesh  2017    2579
15     8      SriLanka  2017    2563
16     1       England  2018    4397
17     2         India  2018    5310
18     3    NewZealand  2018    3712
19     4   SouthAfrica  2018    2834
20     5      Pakistan  2018    3663
21     6     Australia  2018    3888
22     7    Bangladesh  2018    2579
23     8      SriLanka  2018    2463


In [4]:
grouped = df_team.groupby('year')
print(grouped.get_group(2018))

    rank         team  year  points
16     1      England  2018    4397
17     2        India  2018    5310
18     3   NewZealand  2018    3712
19     4  SouthAfrica  2018    2834
20     5     Pakistan  2018    3663
21     6    Australia  2018    3888
22     7   Bangladesh  2018    2579
23     8     SriLanka  2018    2463


In [5]:
print(df_team.columns) #menampilkan nama setiap kolom

Index(['rank', 'team', 'year', 'points'], dtype='object')


In [6]:
print(df_team['points']) #mengakses kolom points

0     4397
1     5310
2     3712
3     2834
4     3663
5     3888
6     2579
7     2463
8     4366
9     5710
10    3812
11    3834
12    3663
13    3088
14    2579
15    2563
16    4397
17    5310
18    3712
19    2834
20    3663
21    3888
22    2579
23    2463
Name: points, dtype: int64


In [7]:
print(df_team.iloc[5]) #mengakses baris ke-6, indeks dimulai dari 0

rank              6
team      Australia
year           2016
points         3888
Name: 5, dtype: object


In [8]:
print(df_team['points'].iloc[10]) #mengakses kolom points baris ke-11

3812


In [9]:
print(df_team['points'].iloc[5:10]) #menampilkan data kolom points baris ke-6 sampai kurang dari 11

5    3888
6    2579
7    2463
8    4366
9    5710
Name: points, dtype: int64


In [10]:
#menggabungkan dataset
#concatenating data
left_team =pd.DataFrame({
             'rank':  [1,2,3,4,5,6,7,8],
              'team':  [
                       'England','India','NewZealand','SouthAfrica',
                       'Pakistan','Australia', 'Bangladesh', 'SriLanka'
                      ],
              'rating':['126','121','112','111','102','100','93','79']
            })

right_team =pd.DataFrame({
              'rank':[1,2,3,4,5,6,7,8],
              'team': [ 
                        'India','England','SouthAfrica','NewZealand',
                         'Australia', 'SriLanka', 'Pakistan','WestIndies'
                       ],
              'rating':['126','121','112','111','102','100','93','79']
             })

In [11]:
print(left_team,"\n\n",right_team)

   rank         team rating
0     1      England    126
1     2        India    121
2     3   NewZealand    112
3     4  SouthAfrica    111
4     5     Pakistan    102
5     6    Australia    100
6     7   Bangladesh     93
7     8     SriLanka     79 

    rank         team rating
0     1        India    126
1     2      England    121
2     3  SouthAfrica    112
3     4   NewZealand    111
4     5    Australia    102
5     6     SriLanka    100
6     7     Pakistan     93
7     8   WestIndies     79


In [12]:
print(pd.concat([left_team,right_team]))

   rank         team rating
0     1      England    126
1     2        India    121
2     3   NewZealand    112
3     4  SouthAfrica    111
4     5     Pakistan    102
5     6    Australia    100
6     7   Bangladesh     93
7     8     SriLanka     79
0     1        India    126
1     2      England    121
2     3  SouthAfrica    112
3     4   NewZealand    111
4     5    Australia    102
5     6     SriLanka    100
6     7     Pakistan     93
7     8   WestIndies     79


In [13]:
#merging data
outer=pd.merge(left_team, right_team,how='outer', on='team')
print(outer)

   rank_x         team rating_x  rank_y rating_y
0     1.0      England      126     2.0      121
1     2.0        India      121     1.0      126
2     3.0   NewZealand      112     4.0      111
3     4.0  SouthAfrica      111     3.0      112
4     5.0     Pakistan      102     7.0       93
5     6.0    Australia      100     5.0      102
6     7.0   Bangladesh       93     NaN      NaN
7     8.0     SriLanka       79     6.0      100
8     NaN   WestIndies      NaN     8.0       79


In [14]:
inner=pd.merge(left_team, right_team,how='inner', on='team')
print(inner)

   rank_x         team rating_x  rank_y rating_y
0       1      England      126       2      121
1       2        India      121       1      126
2       3   NewZealand      112       4      111
3       4  SouthAfrica      111       3      112
4       5     Pakistan      102       7       93
5       6    Australia      100       5      102
6       8     SriLanka       79       6      100


In [15]:
left=pd.merge(left_team, right_team,how='left', on='team')
print(left)

   rank_x         team rating_x  rank_y rating_y
0       1      England      126     2.0      121
1       2        India      121     1.0      126
2       3   NewZealand      112     4.0      111
3       4  SouthAfrica      111     3.0      112
4       5     Pakistan      102     7.0       93
5       6    Australia      100     5.0      102
6       7   Bangladesh       93     NaN      NaN
7       8     SriLanka       79     6.0      100


In [16]:
right=pd.merge(left_team, right_team,how='right', on='team')
print(right)

   rank_x         team rating_x  rank_y rating_y
0     1.0      England      126       2      121
1     2.0        India      121       1      126
2     3.0   NewZealand      112       4      111
3     4.0  SouthAfrica      111       3      112
4     5.0     Pakistan      102       7       93
5     6.0    Australia      100       5      102
6     8.0     SriLanka       79       6      100
7     NaN   WestIndies      NaN       8       79


## Data Cleansing

80% tugas data science adalah data cleansing

In [17]:
#menghapus data yang sama
data=pd.DataFrame({'k1':['one','two']*3+['two'],
                  'k2':[1,1,2,3,3,4,4,]}) #['one','two']*3 diulang sebanyak 3 kali
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [18]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [19]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [20]:
data['v1']=range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [21]:
data['v1']=pd.DataFrame([2,4,6,8,10,12,14])
data

k1  k2  v1
0  one   1   2
1  two   1   4
2  one   2   6
3  two   3   8
4  one   3  10
5  two   4  12
6  two   4  14

In [22]:
data_baru=data.drop_duplicates(['k1'])
data_baru

k1  k2  v1
0  one   1   2
1  two   1   4

In [23]:
data_baru2=data.drop_duplicates(['k2'])
data_baru2

k1  k2  v1
0  one   1   2
2  one   2   6
3  two   3   8
5  two   4  12

In [24]:
data_baru3=data.drop_duplicates(['v1'])
data_baru3

k1  k2  v1
0  one   1   2
1  two   1   4
2  one   2   6
3  two   3   8
4  one   3  10
5  two   4  12
6  two   4  14

In [25]:
#mengganti data
contoh=pd.Series([1,10,9,5,7,11,13,24,3,20])
contoh

0     1
1    10
2     9
3     5
4     7
5    11
6    13
7    24
8     3
9    20
dtype: int64

In [26]:
contoh1=contoh.replace(24,14)
contoh1

0     1
1    10
2     9
3     5
4     7
5    11
6    13
7    14
8     3
9    20
dtype: int64

In [27]:
contoh2=contoh.replace(20,10)
contoh2

0     1
1    10
2     9
3     5
4     7
5    11
6    13
7    24
8     3
9    10
dtype: int64

In [28]:
contoh3=contoh.replace([20,24],10)
contoh3

0     1
1    10
2     9
3     5
4     7
5    11
6    13
7    10
8     3
9    10
dtype: int64

In [29]:
contoh4=contoh.replace([20,24],[10,14])
contoh4

0     1
1    10
2     9
3     5
4     7
5    11
6    13
7    14
8     3
9    10
dtype: int64

In [30]:
#mengubah nama baris dan kolom
tabel={'Kuis':[70,80,87,77],
       'UTS':[83,86,88,84],
       'UAS':[79,81,90,91]}
tabel_df=pd.DataFrame(tabel,index=['Siti','Renol','Arif','Aidil'])
tabel_df

Kuis  UTS  UAS
Siti     70   83   79
Renol    80   86   81
Arif     87   88   90
Aidil    77   84   91

In [31]:
tabel_baru=tabel_df.rename(index={'Aidil':'Fanny'},
                        columns={'Kuis':'Tugas'})
tabel_baru

Tugas  UTS  UAS
Siti      70   83   79
Renol     80   86   81
Arif      87   88   90
Fanny     77   84   91

In [32]:
tabel_baru['Kuis']=pd.Series([80,85,87,81],
                            index=['Siti','Renol','Arif','Fanny'])
tabel_baru

Tugas  UTS  UAS  Kuis
Siti      70   83   79    80
Renol     80   86   81    85
Arif      87   88   90    87
Fanny     77   84   91    81

In [33]:
bb=tabel_baru.replace(70,90)
bb

Tugas  UTS  UAS  Kuis
Siti      90   83   79    80
Renol     80   86   81    85
Arif      87   88   90    87
Fanny     77   84   91    81

### Missing value

Pada suatu dataset, ada kalanya data yang akan dianalisa tidak lengkap. Hal ini akan membuat hasil analisa tidak akurat. 
Kehilangan data bisa diatasi dengan berbagai cara. Bahkan, melakukan penghapusan data juga merupakan solusi yang bisa menjadi pilihan apabila jika dirasa mengisi nilai kosong akan memberikan pengaruh yang kurang bagus terhadap analisa, atau apabila pertimbangan data yang dihapus atau data yang hilang sedikit dan tidak memberikan terlalu banyak sumbangsih untuk analisa yang akan dilakukan. Penghapusan data bisa langsung pada baris data tersebut atau langsung satu kolom data. Pada solusi kedua yaitu menggunakan imputation (pengisian data yang kosong) bisa tergantung dari permasalahannya. Khusus untuk masalah yang berhubungan peramalan tergantung dari data yang ada (lebih lengkap bisa dilihat pada gambar di ppt). Khusus untuk general problem tergantung jenis datanya. Jika yang hilang data kategorikal atau bersifat string bisa menggunakan relasi antar kolom dengan Logistic Regression, jika numerical bisa menggunakan statistik sederhana dan linear regression.

In [34]:
df = np.random.randn(5, 3)
print(df)

[[-1.16948137  0.32720517 -1.89868617]
 [ 0.6577561   0.90310608  0.73153056]
 [ 0.57813702  0.96639781 -0.96023025]
 [ 1.40032813  2.34961301 -0.5511971 ]
 [ 0.5377999   0.56115602 -0.0717551 ]]


In [35]:
df = pd.DataFrame(df, index=['a', 'c', 'e', 'f',
'h'],columns=['one', 'two', 'three'])
print(df)

        one       two     three
a -1.169481  0.327205 -1.898686
c  0.657756  0.903106  0.731531
e  0.578137  0.966398 -0.960230
f  1.400328  2.349613 -0.551197
h  0.537800  0.561156 -0.071755


In [36]:
df = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
print(df)

        one       two     three
a -1.169481  0.327205 -1.898686
b       NaN       NaN       NaN
c  0.657756  0.903106  0.731531
d       NaN       NaN       NaN
e  0.578137  0.966398 -0.960230
f  1.400328  2.349613 -0.551197
g       NaN       NaN       NaN
h  0.537800  0.561156 -0.071755


In [37]:
print(df.isnull().values.any())

True


In [38]:
print(df['one'].isnull())

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool


In [39]:
#mengatasi missing value dengan menghapus data yang kosong 
print(df.dropna())

        one       two     three
a -1.169481  0.327205 -1.898686
c  0.657756  0.903106  0.731531
e  0.578137  0.966398 -0.960230
f  1.400328  2.349613 -0.551197
h  0.537800  0.561156 -0.071755


In [40]:
#mengatasi missing value dengan mean
print(df.mean()) #memeriksa mean setiap kolom

one      0.400908
two      1.021496
three   -0.550068
dtype: float64


In [41]:
df_mean=df.fillna(df.mean()) #mengisi data dengan mean
print("Dataset yang sudah diproses missing value dengan mean :")
print(df_mean)

Dataset yang sudah diproses missing value dengan mean :
        one       two     three
a -1.169481  0.327205 -1.898686
b  0.400908  1.021496 -0.550068
c  0.657756  0.903106  0.731531
d  0.400908  1.021496 -0.550068
e  0.578137  0.966398 -0.960230
f  1.400328  2.349613 -0.551197
g  0.400908  1.021496 -0.550068
h  0.537800  0.561156 -0.071755


In [42]:
#mengatasi missing data dengan median
print(df.median())

one      0.578137
two      0.903106
three   -0.551197
dtype: float64


In [43]:
df_median=df.fillna(df.median()) #mengisi data dengan median
print("Dataset yang sudah diproses missing value dengan median :")
print(df_median)

Dataset yang sudah diproses missing value dengan median :
        one       two     three
a -1.169481  0.327205 -1.898686
b  0.578137  0.903106 -0.551197
c  0.657756  0.903106  0.731531
d  0.578137  0.903106 -0.551197
e  0.578137  0.966398 -0.960230
f  1.400328  2.349613 -0.551197
g  0.578137  0.903106 -0.551197
h  0.537800  0.561156 -0.071755
